### ISSUE TITLE
[BUG] gzdoom.pk3 is not found

### ISSUE THREAD

**Issue by dhwz** [ZDoom-Official/gzdoom#1615]
### GZDoom version

current git version

### Which game are you running with GZDoom?

Doom

### What Operating System are you using?

Other

### Please describe your specific OS version

Linux ARM

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

gzdoom.pk3 is no longer found
gzdoom seems to no longers search for it in IWADSearch.Directories or FileSearch.Directories, I can only start gzdoom if I cd to the path where the gzdoom.pk3 is located.
It also doesn't lookup in ~/.config/gzdoom (that folder is symlinked to /storage/.config/distribution/gzdoom in my case, where the gzdoom.pk3 and game_support.pk3 are located) which should be the default gamedir right?

Did something change there? I saw you did some changes to the startup code maybe something broke there?

### Your configuration

```ini
# This file was generated by GZDoom g4.8pre-428-gc4550ed6c on 2022-05-26 12:01:07
# These are the directories to automatically search for IWADs.
# Each directory should be on a separate line, preceded by Path=
[IWADSearch.Directories]
Path=.
Path=$DOOMWADDIR
Path=/storage/.config/distribution/gzdoom
Path=/storage/roms/doom

# These are the directories to search for wads added with the -file
# command line parameter, if they cannot be found with the path
# as-is. Layout is the same as for IWADSearch.Directories
[FileSearch.Directories]
Path=/storage/.config/distribution/gzdoom
Path=/storage/roms/doom
Path=$DOOMWADDIR

# These are the directories to search for soundfonts that let listed in the menu.
# Layout is the same as for IWADSearch.Directories
[SoundfontSearch.Directories]
Path=/storage/.config/distribution/gzdoom/soundfonts
Path=/storage/.config/distribution/gzdoom/fm_banks
```

### Provide a Log

GZDoom g4.8pre-428-gc4550ed6c - 2022-05-19 19:48:11 +0200 - SDL version
Compiled on May 19 2022

Cannot find gzdoom.pk3

*** Fatal Error ***

**Comment by bobbyboy5069** [comment]
The AUR has a [patch](https://aur.archlinux.org/cgit/aur.git/tree/0001-Fix-file-paths.patch?h=gzdoom) which fixes this, in the first hunk set `progdir` to whatever directory has gzdoom.pk3.

**Comment by dhwz** [comment]
@bobbyboy5069 thanks

**Comment by remyabel2** [comment]
> The AUR has a [patch](https://aur.archlinux.org/cgit/aur.git/tree/0001-Fix-file-paths.patch?h=gzdoom) which fixes this, in the first hunk set `progdir` to whatever directory has gzdoom.pk3.

Yeah I don't think that fixes the issue. The patch is from 2020 and the issue still persists. I did a git bisect and the offending commit appears to be `010f41a3aad3719b1e5d4d8ce157a5d9b0077b44`. Still investigating what the actual issue is though.

**Comment by remyabel2** [comment]
This appears to work, try this patch:

```
diff --git a/src/d_main.cpp b/src/d_main.cpp
index b28bd24f6..a3804c6cc 100644
--- a/src/d_main.cpp
+++ b/src/d_main.cpp
@@ -3532,7 +3532,10 @@ static int D_DoomMain_Internal (void)

        std::set_new_handler(NewFailure);
        const char *batchout = Args->CheckValue("-errorlog");
-
+
+       C_InitConsole(80*8, 25*8, false);
+       I_DetectOS();
+
        // [RH] Make sure zdoom.pk3 is always loaded,
        // as it contains magic stuff we need.
        wad = BaseFileSearch(BASEWAD, NULL, true, GameConfig);
@@ -3542,9 +3545,6 @@ static int D_DoomMain_Internal (void)
        }
        LoadHexFont(wad);       // load hex font early so we have it during startup.

-       C_InitConsole(80*8, 25*8, false);
-       I_DetectOS();
-
        // +logfile gets checked too late to catch the full startup log in the logfile so do some extra check for it here.
        FString logfile = Args->TakeValue("+logfile");
        if (logfile.IsNotEmpty())
```

Don't know enough about the codebase about any potential consequences though.

**Comment by remyabel2** [comment]
Ignore my previous (deleted) comment. I can confirm that reverting the commit fixes the issue.

**Comment by dhwz** [comment]
Hm ok let's see what @coelckers says

**Comment by bobbyboy5069** [comment]
>Yeah I don't think that fixes the issue.

Well that's weird, because I had that issue when installing any recent commit and applying the patch fixed it.
Granted, I did set the `progdir` to `/usr/share/gzdoom` instead of `/usr/lib/gzdoom` and I also set INSTALL_PK3_DIR to `/usr/share/gzdoom` in my build script.

**Comment by remyabel2** [comment]
You say it's "weird" but didn't mention you edited the patch beforehand. And yes we're setting `INSTALL_PK3_PATH` in the spec.

Regardless, I think an actual fix is better than hardcoding the `progdir` and don't know enough about the codebase other than reverting the bad commit I identified works.

**Comment by nazunalika** [comment]
I reverted the commit mentioned by @remyabel2 in this build and we can confirm that it works : https://copr.fedorainfracloud.org/coprs/nalika/gzdoom/build/4504410/

**Comment by chewi** [comment]
Hit this on Gentoo too. I was half way through a git bisect when I found this. Thanks for saving me some effort. :smile:

**Comment by LoneFox78** [comment]
This is trying to use contents of the configuration file (<code>GameConfig</code> variable):
https://github.com/coelckers/gzdoom/blob/f1dec835d7420b52881d3cbf415b39d2478f523f/src/d_main.cpp#L3540
But the file isn't read until here, so it is empty at that point:
https://github.com/coelckers/gzdoom/blob/f1dec835d7420b52881d3cbf415b39d2478f523f/src/d_main.cpp#L3571

**Comment by chewi** [comment]
It's a bit sad that 4.8.1 went out without this being fixed. Is that why there are only Windows binaries available? I still haven't bumped the Gentoo Linux package because of it. I see OpenSUSE reverted the offending commit, but I wasn't sure whether that was safe.

**Comment by madame-rachelle** [comment]
Is this still an issue? A PR was submitted that addresses this.

**Comment by jengelh** [comment]
#1665 resolves the issue for me and openSUSE.

**Comment by dhwz** [comment]
Does someone know if it was also applied to the raze engine else I'll open another issue there.

**Comment by mjr4077au** [comment]
> Does someone know if it was also applied to the raze engine else I'll open another issue there.

I'll take a look within an hour.

**Comment by eliw00d** [comment]
Could a 4.8.3 release be created that includes this fix?

**Comment by adcdam** [comment]
> Could a 4.8.3 release be created that includes this fix? 
hi @eliw00d i dont know what distro are you using but i made a patch for gzdoom 4.8.2 if you compile the package and add this package it should work.

https://pastebin.com/dJrM2Dbv

**Comment by eliw00d** [comment]
> hi @eliw00d i dont know what distro are you using but i made a patch for gzdoom 4.8.2 if you compile the package and add this patch it should work.
> 
> https://pastebin.com/dJrM2Dbv

I am currently using Flathub and they manually added the patch. They suggested asking for an official release so I was just trying to help out.
